Insert into Building values (1, 'Alumni Hall' );
Insert into Building values (2, 'Austin Hall' );
Insert into Building values (3, 'Corr Hall' );
Insert into Building values (4, 'Delurey Hall' );
Insert into Building values (5, 'Fedigan Hall' );
Insert into Building values (6, 'Moriarty Hall' );
Insert into Building values (7, 'O Dwyer Hall' );
Insert into Building values (8, 'Sheehan Hall' );
Insert into Building values (9, 'Simpson Hall' );
Insert into Building values (10, 'Sullivan Hall' );
Insert into Building values (11, 'St. Rita’s Hall' );
Insert into Building values (12, 'Caughlin Hall' );
Insert into Building values (13, 'Good Counsel Hall' );
Insert into Building values (14, 'McGuire Hall' );
Insert into Building values (15, 'Stanford Hall' );
Insert into Building values (16, 'Katharine Hall' );
Insert into Building values (17, 'St. Monica Hall' );
Insert into Building values (18, 'Farley Hall' );
Insert into Building values (19, 'Gallen Hall' );
Insert into Building values (20, 'Jackson Hall' );
Insert into Building values (21, 'Klekotka Hall' );
Insert into Building values (22, 'Moulden Hall' );
Insert into Building values (23, 'Rudolph Hall' );
Insert into Building values (24, 'St. Clare Hall' );
Insert into Building values (25, 'St. Marys Hall' );
Insert into Building values (26, 'Welsh Hall' );
Insert into Building values (27, 'Arch Hall' );
Insert into Building values (28, 'Trinity Hall' );
Insert into Building values (29, 'Canon Hall' );
Insert into Building values (30, 'Chapter Hall' );
Insert into Building values (31, 'Cupola Hall' );
Insert into Building values (32, 'Friar Hall' );
Insert into Building values (33, 'Dougherty Hall' );
Insert into Building values (34, 'Bartley Hall' );
Insert into Building values (35, 'CEER' );
Insert into Building values (36, 'Connelly Center' );
Insert into Building values (37, 'Driscoll Hall' );
Insert into Building values (38, 'Cafe Nova' );
Insert into Building values (39, 'Falvey Memorial Library' );
Insert into Building values (40, 'St. Augustine Center for the Liberal Arts' );
Insert into Building values (41, 'Donahue Hall' );
Insert into Building values (42, 'The Commons' );
Insert into Building values (43, 'Law School' );
