Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (0,18, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (1,9, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (2,15, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (3,3, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (4,8, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (5,6, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (6,1, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (7,10, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (8,14, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (9,3, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (10,16, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (11,17, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (12,18, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (13,2, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (14,4, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (15,11, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (16,8, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (17,11, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (18,19, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (19,8, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (20,19, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (21,17, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (22,9, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (23,11, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (24,1, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (25,10, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (26,18, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (27,11, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (28,14, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (29,7, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (30,13, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (31,13, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (32,18, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (33,19, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (34,6, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (35,1, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (36,3, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (37,8, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (38,10, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (39,4, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (40,14, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (41,19, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (42,19, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (43,9, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (44,13, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (45,3, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (46,13, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (47,12, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (48,16, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (49,11, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (50,4, 'Dine in' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (51,12, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (52,7, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (53,13, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (54,6, 'Delivery' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (55,17, 'Pick-up' );
Insert into delivery_details (Delivery_id,Dining_id,Delivery_type) values (56,8, 'Dine in' );
