Insert into dining_place (Dining_id,Building_id,Dining_name) values (1,33, 'Dougherty Dining Hall' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (2,34, 'The Curley Exchange' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (3,34, 'Holy Grounds ' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (4,35, 'Holy Grounds' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (5,35, 'Belle Air Terrace ' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (6,36, 'Freshens' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (7,36, 'Holy Grounds ' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (8,37, 'The Recovery Room ' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (9,38, 'Cafe Nova' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (10,39, 'Holy Grounds' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (11,40, 'St. Augustine Cafe' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (12,36, 'Connelly Convenience' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (13,41, 'The Court' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (14,41, 'Donahue Market' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (15,42, 'Holy Grounds' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (16,25, 'St. Mary s Dining Hall' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (17,43, 'The Law School Cafe' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (18,43, 'Legal Grounds' );
Insert into dining_place (Dining_id,Building_id,Dining_name) values (19,25, 'Second Storey' );
